name: Development Workflow

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Node/Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm test
